name = "backend"
compatibility_date = "2023-12-01"

 [vars]
 MY_VAR = "my-variable"

 
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjJiMjFhNjQtNTk4NS00ZGQ4LTk0YTYtNjRjNTc0OGNmMTc1IiwidGVuYW50X2lkIjoiM2IxMDIxNDQzMGFhYTQ1ZjAwMzNjNmQ3Yzc4NzMyYzM5ODRkN2M0NGY1ZDNiODlhOWI4Y2E1MGJiNTdhMDRjMCIsImludGVybmFsX3NlY3JldCI6IjY2YWE1ODg1LWM5YTQtNDJlMC1hM2M1LTE1ZmIyZmRhMzAyYiJ9.CJh6Ly1HoNNZiOkId2HdlIApBMDukRbFx4lS8AhdTKE"

SECRET_KEY="052e7219d09f20dc3b484bc7e8bcf6d808b5b5bbdf74c2273aca72194ba0fcb5"